# docker-compose.yml
version: "3.3"
services:
  postgres:
    image: postgres
    hostname: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    networks:
      mynet:
        ipv4_address: 0.0.15.0

  namenode:
   build: ./namenode
   hostname: namenode
   # env_file: ./datanode1/.env
   depends_on:
     - postgres
   links:
     - postgres
   ports:
     - 3002:3002
   environment:
     WAIT_HOSTS: postgres:5432
   networks:
      mynet:
        ipv4_address: 0.0.15.1

  datanode1:
    build: ./datanode1
    hostname: datanode1
    # env_file: ./datanode1/.env
    depends_on:
     - postgres
    links:
     - postgres
    ports:
     - 3001:3001
    environment:
     WAIT_HOSTS: postgres:5432
    networks:
      mynet:
        ipv4_address: 0.0.15.2

  datanode2:
    build: ./datanode2
    hostname: datanode2
    # env_file: ./datanode2/.env
    ports:
     - 4000:4000
    depends_on:
     - postgres
    links:
     - postgres
    environment:
     WAIT_HOSTS: postgres:5432
    networks:
      mynet:
        ipv4_address: 0.0.15.3


networks:
  mynet:
    driver: bridge
    ipam:
      config:
        - subnet: 0.0.15.0/8